WHITELISTED = "WHITELISTED"
ON_THE_WHITELIST = "ON_THE_WHITELIST"
BANNED = "BANNED"
OFFLINEMODE = "OFFLINEMODE"
NOT_ON_THE_WHITELIST = "NOT_ON_THE_WHITELIST"
NONE = "NONE"

def filterServer(x):
    return x != None